name: Status Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'  # Каждые 12 часов

jobs:
  check-status:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check dev server readiness
      run: |
        echo "🔍 Проверка готовности dev сервера..."
        
        # Проверяем, что все зависимости установлены
        echo "📦 Проверка зависимостей..."
        npm list --depth=0
        
        # Проверяем, что скрипты доступны
        echo "🔧 Проверка скриптов..."
        npm run --silent dev --help || echo "Dev скрипт найден"
        
        # Проверяем конфигурацию Next.js
        echo "⚙️ Проверка конфигурации Next.js..."
        if [ -f "next.config.ts" ]; then
          echo "✅ next.config.ts найден"
        else
          echo "❌ next.config.ts не найден"
        fi
        
        # Проверяем основные файлы
        echo "📁 Проверка структуры проекта..."
        if [ -d "src/app" ]; then
          echo "✅ src/app директория найдена"
        else
          echo "❌ src/app директория не найдена"
        fi
        
        if [ -f "package.json" ]; then
          echo "✅ package.json найден"
          echo "📋 Версия проекта: $(node -p "require('./package.json').version")"
        else
          echo "❌ package.json не найден"
        fi
        
        echo "✅ Проверка завершена успешно!"
        
    - name: Create status page
      run: |
        mkdir -p public
        cat > public/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="ru">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Solar Studio Web - Status</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    min-height: 100vh;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }
                .container {
                    text-align: center;
                    max-width: 700px;
                    padding: 2rem;
                    background: rgba(255,255,255,0.1);
                    border-radius: 20px;
                    backdrop-filter: blur(10px);
                    box-shadow: 0 8px 32px rgba(0,0,0,0.3);
                }
                .status-badge {
                    display: inline-block;
                    background: #2ecc71;
                    color: white;
                    padding: 0.5rem 1rem;
                    border-radius: 25px;
                    font-weight: bold;
                    margin: 1rem 0;
                }
                .command-box {
                    background: rgba(0,0,0,0.3);
                    padding: 1.5rem;
                    border-radius: 15px;
                    margin: 1.5rem 0;
                    font-family: 'Courier New', monospace;
                    text-align: left;
                }
                .btn {
                    display: inline-block;
                    background: linear-gradient(45deg, #ff6b6b, #4ecdc4);
                    color: white;
                    padding: 1rem 2rem;
                    text-decoration: none;
                    border-radius: 50px;
                    margin: 0.5rem;
                    transition: transform 0.3s ease;
                    font-weight: bold;
                }
                .btn:hover { transform: translateY(-2px); }
                .info-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 1rem;
                    margin: 2rem 0;
                }
                .info-card {
                    background: rgba(255,255,255,0.1);
                    padding: 1rem;
                    border-radius: 10px;
                    border-left: 4px solid #4ecdc4;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 Solar Studio Web</h1>
                <p style="font-size: 1.2rem; margin: 1rem 0;">Next.js приложение для студии разработки игрового контента</p>
                
                <div class="status-badge">✅ Готов к запуску</div>
                
                <div class="command-box">
                    <div><strong>Локальный запуск:</strong></div>
                    <div>git clone https://github.com/YOUR_USERNAME/solar-studio-web.git</div>
                    <div>cd solar-studio-web</div>
                    <div>npm install</div>
                    <div>npm run dev</div>
                    <div style="margin-top: 1rem; color: #4ecdc4;">🌐 Откройте: http://localhost:4400</div>
                </div>
                
                <div class="info-grid">
                    <div class="info-card">
                        <h4>🔐 Авторизация</h4>
                        <p>Формы входа и регистрации</p>
                    </div>
                    <div class="info-card">
                        <h4>👤 Личный кабинет</h4>
                        <p>Полнофункциональный dashboard</p>
                    </div>
                    <div class="info-card">
                        <h4>🛍️ Каталог товаров</h4>
                        <p>Интерактивные модальные окна</p>
                    </div>
                    <div class="info-card">
                        <h4>📱 Адаптивность</h4>
                        <p>Работает на всех устройствах</p>
                    </div>
                </div>
                
                <div style="margin: 2rem 0;">
                    <a href="https://github.com/YOUR_USERNAME/solar-studio-web" class="btn" target="_blank">
                        📁 GitHub Repository
                    </a>
                    <a href="https://github.com/YOUR_USERNAME/solar-studio-web/actions" class="btn" target="_blank">
                        🔄 GitHub Actions
                    </a>
                </div>
                
                <div style="font-size: 0.9rem; opacity: 0.8; margin-top: 2rem;">
                    <p>Последняя проверка: <span id="timestamp"></span></p>
                    <p>Статус: Dev сервер готов к запуску</p>
                </div>
            </div>
            
            <script>
                document.getElementById('timestamp').textContent = new Date().toLocaleString('ru-RU');
            </script>
        </body>
        </html>
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
